### ISSUE TITLE
parallel environment parsing 2.0.0a

### ISSUE THREAD

**Issue by mvrequa** [Azure/cyclecloud-gridengine#4]
ge version 8.6.7-demo
Traceback (most recent call last):
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/cli.py", line 562, in main
    args.func(**kwargs)
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/cli.py", line 37, in autoscale
    autoscaler.autoscale_grid_engine(config, ctx_handler=ctx_handler)
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/autoscaler.py", line 31, in autoscale_grid_engine
    ge_driver = GridEngineDriver(config)
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/driver.py", line 75, in __init__
    jobs, scheduler_nodes = _get_jobs_and_nodes(autoscale_config)
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/driver.py", line 397, in _get_jobs_and_nodes
    parallel_environments.read_queue_configs(autoscale_config), lambda q: q.qname
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/parallel_environments.py", line 61, in read_queue_configs
    ge_queues.append(GridEngineQueue(queue_config, autoscale_config, constraints))
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/parallel_environments.py", line 218, in __init__
    self.__parallel_environments[pe_name] = all_pes[pe_name]
KeyError: 'make'

**Comment by mvrequa** [comment]
[root@ip-0A050006 ~]# qconf -spl
OpenMP
mpi
mpislots
smpslots

**Comment by mvrequa** [comment]
Resolved with commit 
https://github.com/Azure/cyclecloud-gridengine/commit/ad1580ee85802774e8a6160d5f03d017feb4f9dc

Occurs when PE is expressed in a queue definition, but is not a valid pe. In 8.6.7-demo make is not included as a PE by default.

Added a make definition.
