### ISSUE TITLE
initialize sqlite db upon autoscale call if not already initialized

### ISSUE THREAD

**Issue by mvrequa** [Azure/cyclecloud-gridengine#5]
Running the autoscaler can encounter this:

2020-07-09 19:48:29,879 ERROR: Error while opening file:///opt/cycle/jetpack/system/bootstrap/gridengine/nodehistory.db?mode=ro - unable to open database file
Traceback (most recent call last):
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/hpc/autoscale/node/nodehistory.py", line 64, in initialize_db
    conn = sqlite3.connect(file_uri, uri=True)
sqlite3.OperationalError: unable to open database file
unable to open database file
Traceback (most recent call last):
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/cli.py", line 779, in main
    args.func(**kwargs)
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/cli.py", line 45, in autoscale
    autoscaler.autoscale_grid_engine(config, ctx_handler=ctx_handler)
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/autoscaler.py", line 58, in autoscale_grid_engine
    demand_calculator = calculate_demand(config, ge_driver, ctx_handler, node_history)
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/autoscaler.py", line 173, in calculate_demand
    config, ge_driver, ctx_handler, node_history
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/gridengine/autoscaler.py", line 154, in new_demand_calculator
    node_history = SQLiteNodeHistory(db_path, read_only)
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/hpc/autoscale/node/nodehistory.py", line 111, in __init__
    self.conn = initialize_db(path, read_only)
  File "/opt/cycle/jetpack/system/bootstrap/gridenginevenv/lib/python3.6/site-packages/hpc/autoscale/node/nodehistory.py", line 64, in initialize_db
    conn = sqlite3.connect(file_uri, uri=True)
sqlite3.OperationalError: unable to open database file

**Comment by mvrequa** [comment]
Closed
